name: jupyter-demo
dependencies:
- ipykernel=4.1.1
- ipyparallel=4.0.2
- ipython=4.0.0
- ipython_genutils=0.1.0
- ipywidgets=4.1.0
- jupyter=1.0.0
- jupyter_client=4.1.1
- jupyter_console=4.0.3
- jupyter_core=4.0.6
- matplotlib=1.5.0
- nbconvert=4.0.0
- nbformat=4.0.1
- notebook=4.0.6
- numpy=1.10.1
- pandas=0.17.1
- python=3.5.0
- pyzmq=14.7.0
- scipy=0.16.0
- seaborn=0.6.0
- setuptools=18.5
- tornado=4.3
- traitlets=4.0.0
- zeromq=4.1.3


